INSERT INTO aspire.employee (`id`, `name`, `stream_id`, `account_id`, `manager_id`, `designation`) VALUES 
(1, 'Daniel Allen', 'IND-ASP-AI-DELIVERY', 'IND-ASP-AI', 0, 'Manager'),
(2, 'Chloe King', 'IND-ASP-BC-DELIVERY', 'IND-ASP-BC', 0, 'Manager'),
(3, 'Matthew Wright', 'IND-ASP-CC-DELIVERY', 'IND-ASP-CC', 0, 'Manager'),
(4, 'Lily Scott', 'IND-ASP-CS-DELIVERY', 'IND-ASP-CS', 0, 'Manager'),
(5, 'Jackson Green', 'IND-ASP-ML-DELIVERY', 'IND-ASP-ML', 0, 'Manager'),
(6, 'Aria Adams', 'IND-ASP-SAAS-DELIVERY', 'IND-ASP-SAAS', 0, 'Manager'),
(7, 'Aiden Nelson', 'IND-ASP-AI-DELIVERY', 'IND-ASP-AI', 1, 'Associate'),
(8, 'Zoe Carter', 'IND-ASP-BC-DELIVERY', 'IND-ASP-BC', 2, 'Associate'),
(9, 'Gabriel Mitchell', 'IND-ASP-CC-DELIVERY', 'IND-ASP-CC', 3, 'Associate'),
(10, 'Nora Perez', 'IND-ASP-CS-DELIVERY', 'IND-ASP-CS', 4, 'Associate'),
(11, 'Anthony Roberts', 'IND-ASP-ML-DELIVERY', 'IND-ASP-ML', 5, 'Associate'),
(12, 'Ruby Turner', 'IND-ASP-SAAS-DELIVERY', 'IND-ASP-SAAS', 6, 'Associate'),
(13, 'Isaac Phillips', 'IND-ASP-AI-DELIVERY', 'IND-ASP-AI', 1, 'Associate'),
(14, 'Hannah Campbell', 'IND-ASP-BC-DELIVERY', 'IND-ASP-BC', 2, 'Associate'),
(15, 'Samuel Parker', 'IND-ASP-CC-DELIVERY', 'IND-ASP-CC', 3, 'Associate'),
(16, 'Layla Evans', 'IND-ASP-CS-DELIVERY', 'IND-ASP-CS', 4, 'Associate'),
(17, 'Christopher Edwards', 'IND-ASP-ML-DELIVERY', 'IND-ASP-ML', 5, 'Associate'),
(18, 'Lila Collins', 'IND-ASP-SAAS-DELIVERY', 'IND-ASP-SAAS', 6, 'Associate');

INSERT INTO aspire.employee (`id`, `name`, `stream_id`, `account_id`, `manager_id`, `designation`) VALUES 
(19, 'David Stewart', 'IND-ASP-AI-DEVELOPMENT', 'IND-ASP-AI', 0, 'Manager'),
(20, 'Stella Sanchez', 'IND-ASP-BC-DEVELOPMENT', 'IND-ASP-BC', 0, 'Manager'),
(21, 'Henry Morris', 'IND-ASP-CC-DEVELOPMENT', 'IND-ASP-CC', 0, 'Manager'),
(22, 'Natalie Rogers', 'IND-ASP-CS-DEVELOPMENT', 'IND-ASP-CS', 0, 'Manager'),
(23, 'Dylan Reed', 'IND-ASP-ML-DEVELOPMENT', 'IND-ASP-ML', 0, 'Manager'),
(24, 'Victoria Cook', 'IND-ASP-SAAS-DEVELOPMENT', 'IND-ASP-SAAS', 0, 'Manager'),
(25, 'Owen Morgan', 'IND-ASP-AI-DEVELOPMENT', 'IND-ASP-AI', 19, 'Associate'),
(26, 'Evelyn Moore', 'IND-ASP-BC-DEVELOPMENT', 'IND-ASP-BC', 20, 'Associate'),
(27, 'Logan Jackson', 'IND-ASP-CC-DEVELOPMENT', 'IND-ASP-CC', 21, 'Associate'),
(28, 'Abigail Martin', 'IND-ASP-CS-DEVELOPMENT', 'IND-ASP-CS', 22, 'Associate'),
(29, 'Alexander Lee', 'IND-ASP-ML-DEVELOPMENT', 'IND-ASP-ML', 23, 'Associate'),
(30, 'Ella Clark', 'IND-ASP-SAAS-DEVELOPMENT', 'IND-ASP-SAAS', 24, 'Associate');

INSERT INTO aspire.employee (`id`, `name`, `stream_id`, `account_id`, `manager_id`, `designation`) VALUES 
(31, 'Jacob Lewis', 'IND-ASP-AI-QA', 'IND-ASP-AI', 0, 'Manager'),
(32, 'Scarlett Walker', 'IND-ASP-BC-QA', 'IND-ASP-BC', 0, 'Manager'),
(33, 'Michael Hall', 'IND-ASP-CC-QA', 'IND-ASP-CC', 0, 'Manager'),
(34, 'Grace Young', 'IND-ASP-CS-QA', 'IND-ASP-CS', 0, 'Manager'),
(35, 'Isabella Hernandez', 'IND-ASP-ML-QA', 'IND-ASP-ML', 0, 'Manager'),
(36, 'Benjamin Lee', 'IND-ASP-SAAS-QA', 'IND-ASP-SAAS', 0, 'Manager'),
(37, 'Mia Lopez', 'IND-ASP-AI-QA', 'IND-ASP-AI', 31, 'Associate'),
(38, 'Elijah Perez', 'IND-ASP-BC-QA', 'IND-ASP-BC', 32, 'Associate'),
(39, 'Amelia Thompson', 'IND-ASP-CC-QA', 'IND-ASP-CC', 33, 'Associate'),
(40, 'Lucas White', 'IND-ASP-CS-QA', 'IND-ASP-CS', 34, 'Associate'),
(41, 'Harper Anderson', 'IND-ASP-ML-QA', 'IND-ASP-ML', 35, 'Associate'),
(42, 'Mason Taylor', 'IND-ASP-SAAS-QA', 'IND-ASP-SAAS', 36, 'Associate');

INSERT INTO aspire.employee (`id`, `name`, `stream_id`, `account_id`, `manager_id`, `designation`) VALUES 
(43, 'Emma Johnson', 'IND-ASP-AI-SALES', 'IND-ASP-AI', 0, 'Manager'),
(44, 'Liam Smith', 'IND-ASP-BC-SALES', 'IND-ASP-BC', 0, 'Manager'),
(45, 'Olivia Brown', 'IND-ASP-CC-SALES', 'IND-ASP-CC', 0, 'Manager'),
(46, 'Noah Davis', 'IND-ASP-CS-SALES', 'IND-ASP-CS', 0, 'Manager'),
(47, 'Ava Wilson', 'IND-ASP-ML-SALES', 'IND-ASP-ML', 0, 'Manager'),
(48, 'William Martinez', 'IND-ASP-SAAS-SALES', 'IND-ASP-SAAS', 0, 'Manager'),
(49, 'Sophia Garcia', 'IND-ASP-AI-SALES', 'IND-ASP-AI', 43, 'Associate'),
(50, 'James Rodriguez', 'IND-ASP-BC-SALES', 'IND-ASP-BC', 44, 'Associate'),
(51, 'Samuel Sullivan', 'IND-ASP-CC-SALES', 'IND-ASP-CC', 45, 'Associate'),
(52, 'Sarah Simmons', 'IND-ASP-CS-SALES', 'IND-ASP-CS', 46, 'Associate'),
(53, 'Sophia Carter', 'IND-ASP-ML-SALES', 'IND-ASP-ML', 47, 'Associate'),
(54, 'Sebastian Scott', 'IND-ASP-SAAS-SALES', 'IND-ASP-SAAS', 48, 'Associate'),
(55, 'Savannah Blake', 'IND-ASP-AI-SALES', 'IND-ASP-AI', 43, 'Associate'),
(56, 'Silas Shaw', 'IND-ASP-BC-SALES', 'IND-ASP-BC', 44, 'Associate'),
(57, 'Stella Johnson', 'IND-ASP-CC-SALES', 'IND-ASP-CC', 45, 'Associate'),
(58, 'Sienna Lee', 'IND-ASP-CS-SALES', 'IND-ASP-CS', 46, 'Associate'),
(59, 'Oliver Morgan', 'IND-ASP-ML-SALES', 'IND-ASP-ML', 47, 'Associate'),
(60, 'Simon Taylor', 'IND-ASP-SAAS-SALES', 'IND-ASP-SAAS', 48, 'Associate'),
(61, 'Percy Jackson', 'IND-ASP-AI-TESTING', 'IND-ASP-AI', 0, 'Manager');

